---
name: Continuous Deployment

on:
  push:
    branches: [ main, staging ]

jobs:
  #    prod_deploy:
  #        if: ${{ github.ref == 'refs/heads/master' }}
  #        runs-on: ubuntu-latest
  #        steps:
  #            - name: Deploy
  #              uses: appleboy/ssh-action@v0.0.9
  #              with:
  #                  host: ${{ secrets.PROD_HOST }}
  #                  username: ${{ secrets.PROD_USERNAME }}
  #                  key: ${{ secrets.PROD_PRIVATE_SSH_KEY }}
  #
  #                  script_stop: true
  #                  script: |
  #                      cd /var/www/html/mamm-bk
  #                      git pull
  #                      npm ci
  #                      npm run build

  staging_deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        timeout-minutes: 10
        uses: appleboy/ssh-action@v0.0.9
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_SSH_KEY }}

          script_stop: true
          script: |
            cd /var/www/html/mamm-bk
            git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm ci
            pm2 restart all
